"""empty message

Revision ID: 0a6d9d8e6230
Revises: ed0f77e2010c
Create Date: 2022-02-23 22:43:02.188326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6d9d8e6230'
down_revision = 'ed0f77e2010c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'money')
    # ### end Alembic commands ###
