"""empty message

Revision ID: 19bebb367363
Revises: 2d984da7f099
Create Date: 2022-02-22 20:44:09.667782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bebb367363'
down_revision = '2d984da7f099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('icon', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'icon')
    # ### end Alembic commands ###
