"""empty message

Revision ID: 463aba52aad6
Revises: 4cf9f6b084f7
Create Date: 2022-02-23 19:26:55.713638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463aba52aad6'
down_revision = '4cf9f6b084f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xiadan', sa.Column('state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xiadan', 'state')
    # ### end Alembic commands ###
