"""empty message

Revision ID: 4d92813cccaa
Revises: f8c110ae1d3b
Create Date: 2022-02-22 21:06:29.612227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d92813cccaa'
down_revision = 'f8c110ae1d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('icon', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'icon')
    # ### end Alembic commands ###
