"""empty message

Revision ID: ed0f77e2010c
Revises: 463aba52aad6
Create Date: 2022-02-23 22:41:13.268909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0f77e2010c'
down_revision = '463aba52aad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rider')
    # ### end Alembic commands ###
