"""empty message

Revision ID: f8c110ae1d3b
Revises: 19bebb367363
Create Date: 2022-02-22 20:44:52.803556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8c110ae1d3b'
down_revision = '19bebb367363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'icon')
    op.add_column('user', sa.Column('icon', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    op.add_column('answer', sa.Column('icon', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
