"""empty message

Revision ID: fcaa6399d941
Revises: 4d92813cccaa
Create Date: 2022-02-23 13:34:52.274509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaa6399d941'
down_revision = '4d92813cccaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xiadan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dish', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('delivery_address', sa.String(length=200), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xiadan')
    # ### end Alembic commands ###
